// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SC01AConnexionrussieClientTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sC01AConnexionrussieClient() {
    driver.get("http://localhost:8080/_00_ASBank2023/");
    driver.manage().window().setSize(new Dimension(1276, 692));
    assertThat(driver.getTitle(), is("Application IUT Bank"));
    driver.findElement(By.linkText("Page de Login")).click();
    assertThat(driver.getTitle(), is("Page de connexion"));
    driver.findElement(By.id("controller_Connect_login_action_userCde")).click();
    driver.findElement(By.id("controller_Connect_login_action_0")).click();
    assertThat(driver.getTitle(), is("Tableau de bord"));
  }
}
