package com.iut.banque.test.selenium;

// Generated by Selenium IDE (Nettoyé et sécurisé)
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.time.Duration;
import org.openqa.selenium.firefox.FirefoxOptions;

public class TestCreationClient {
    private WebDriver driver;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        // Initialisation du driver Firefox
        FirefoxOptions options = new FirefoxOptions();
        options.addArguments("--headless");
        driver = new FirefoxDriver(options);
        js = (JavascriptExecutor) driver;
    }

    @After
    public void tearDown() {
        // Fermeture du navigateur
        if (driver != null) {
            driver.quit();
        }
    }

    @Test
    public void sC01AConnexionReussieClient() {
        driver.get("http://localhost:8080/_00_ASBank2023/");
        driver.manage().window().setSize(new Dimension(1276, 692));
        driver.findElement(By.linkText("Page de Login")).click();

        // Connexion Client
        WebElement userField = driver.findElement(By.id("controller_Connect_login_action_userCde"));
        js.executeScript("arguments[0].value='client1';", userField);

        WebElement pwdField = driver.findElement(By.name("userPwd"));
        js.executeScript("arguments[0].value='clientpass1';", pwdField);

        driver.findElement(By.xpath("//input[@value='Se Connecter']")).click();

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        // On attend d'être connecté
        wait.until(ExpectedConditions.urlContains("Connect"));

        // On affirme qu'on est bien sur une page de type "Connect" (Client ou Manager).
        String currentUrl = driver.getCurrentUrl();
        assertTrue("L'URL devrait contenir 'Connect' après connexion. Actuelle : " + currentUrl,
                currentUrl.contains("Connect"));
    }

    @Test
    public void sC01BConnexionReussieManager() {
        // 1. Accès à l'accueil
        driver.get("http://localhost:8080/_00_ASBank2023/");
        driver.manage().window().setSize(new Dimension(1276, 692));

        // 2. Login
        driver.findElement(By.linkText("Page de Login")).click();

        // Utilisation de l'ID (plus fiable que name)
        WebElement userField = driver.findElement(By.id("controller_Connect_login_action_userCde"));
        js.executeScript("arguments[0].value='a';", userField);

        WebElement pwdField = driver.findElement(By.name("userPwd"));
        js.executeScript("arguments[0].value='a';", pwdField);

        driver.findElement(By.xpath("//input[@value='Se Connecter']")).click();

        // 5. Attente et Vérification du TITRE
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(5));

        // On attend que le titre DEVIENNE exactement celui attendu
        wait.until(ExpectedConditions.titleIs("Tableau de bord - Gestionnaire"));

        // Assertion finale
        assertThat(driver.getTitle(), is("Tableau de bord - Gestionnaire"));
    }

    @Test
    public void sC02EchecDeConnexionMauvaisIdentifiants() {
        driver.get("http://localhost:8080/_00_ASBank2023/");
        driver.manage().window().setSize(new Dimension(1276, 692));
        driver.findElement(By.linkText("Page de Login")).click();

        WebElement userField = driver.findElement(By.id("controller_Connect_login_action_userCde"));
        js.executeScript("arguments[0].value='inconnu';", userField);

        WebElement pwdField = driver.findElement(By.name("userPwd"));
        js.executeScript("arguments[0].value='0000';", pwdField);

        driver.findElement(By.xpath("//input[@value='Se Connecter']")).click();

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));

        // CORRECTION : L'application redirige vers une page d'erreur spécifique.
        // On attend que le titre contienne "Erreur" OU que l'URL contienne "error".
        // On n'attend PAS le bouton "Se Connecter" car il n'est pas sur la page d'erreur.
        wait.until(ExpectedConditions.or(
                ExpectedConditions.titleContains("Erreur"),
                ExpectedConditions.urlContains("error")
        ));

        // Vérification
        String pageTitle = driver.getTitle();
        assertTrue("Le titre devrait contenir 'Erreur'. Actuel: " + pageTitle,
                pageTitle.contains("Erreur"));
    }

    @Test
    public void sC03Deconnexion() {
        driver.get("http://localhost:8080/_00_ASBank2023/");
        driver.manage().window().setSize(new Dimension(1276, 692));
        driver.findElement(By.linkText("Page de Login")).click();

        // Connexion Client
        WebElement userField = driver.findElement(By.id("controller_Connect_login_action_userCde"));
        js.executeScript("arguments[0].value='client1';", userField);

        WebElement pwdField = driver.findElement(By.name("userPwd"));
        js.executeScript("arguments[0].value='clientpass1';", pwdField);

        driver.findElement(By.xpath("//input[@value='Se Connecter']")).click();

        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        // On attend d'être connecté
        wait.until(ExpectedConditions.urlContains("Connect"));

        // CORRECTION CRITIQUE : Contournement du problème d'encodage (Déconnexion).
        // On cherche un input de type submit dont la valeur "contient" le mot "connexion"
        // (cela marchera pour "Déconnexion" sans risquer le bug de l'accent é/).
        WebElement logoutButton = wait.until(ExpectedConditions.elementToBeClickable(
                By.xpath("//input[@type='submit' and contains(@value, 'connexion')]")
        ));

        logoutButton.click();

        // Vérification retour accueil
        wait.until(ExpectedConditions.titleIs("Application IUT Bank"));
        assertThat(driver.getTitle(), is("Application IUT Bank"));
    }
}